fix

diff --git a/.github/workflows/cherry-pick-rc-to-develop.yml b/.github/workflows/cherry-pick-rc-to-develop.yml
--- a/.github/workflows/cherry-pick-rc-to-develop.yml
+++ b/.github/workflows/cherry-pick-rc-to-develop.yml
@@ -24,43 +24,42 @@ jobs:
       - name: Append -cherry-pick to branch name
         id: extract
         run: |
+          set -x
           PR_BRANCH="${{ github.event.pull_request.head.ref }}"
           NEW_BRANCH_NAME="${PR_BRANCH}-cherry-pick"
           echo "New branch name: $NEW_BRANCH_NAME"
-          echo "::set-output name=newBranchName::$NEW_BRANCH_NAME"
-
-      - name: Check if changes only in kalium submodule
-        id: check_changes
-        run: |
-          NUM_CHANGES=$(git diff origin/develop --name-only | grep -v '^kalium/' | wc -l)
-          if [ "$NUM_CHANGES" -gt 0 ]; then
-            echo "::set-output name=shouldCherryPick::true"
-          else
-            echo "No changes outside of kalium submodule, skipping cherry-pick"
-            echo "::set-output name=shouldCherryPick::false"
-          fi
+          echo "newBranchName=$NEW_BRANCH_NAME" >> $GITHUB_ENV
 
       - uses: fregante/setup-git-user@v2
 
       - name: Cherry-pick commits
         id: cherry
-        if: steps.check_changes.outputs.shouldCherryPick == 'true'
         run: |
+          set -x
           git fetch origin develop:develop
-          git checkout -b ${{ steps.extract.outputs.newBranchName }} develop
+          git checkout -b ${{ env.newBranchName }} develop
           # Cherry-picking the last commit on the base branch
           OUTPUT=$(git cherry-pick ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true)
-          CONFLICTS=$(echo "$OUTPUT" | grep 'CONFLICT')
-          echo "::set-output name=conflicts::$CONFLICTS"
-          git add .
-          git cherry-pick --continue || echo "No cherry-pick in progress"
-          git push origin ${{ steps.extract.outputs.newBranchName }}
+          CONFLICTS=$(echo "$OUTPUT" | grep 'CONFLICT' || echo "")
+          if [ -n "$CONFLICTS" ]; then
+              git add .
+              git cherry-pick --continue || true
+          fi
+          git push origin ${{ env.newBranchName }} || (echo "Failed to push to origin" && exit 1)
+          echo "conflicts=$CONFLICTS" >> $GITHUB_ENV
 
       - name: Create PR
-        if: steps.check_changes.outputs.shouldCherryPick == 'true'
         env:
           PR_TITLE: ${{ github.event.pull_request.title }}
-          PR_BRANCH: ${{ steps.extract.outputs.newBranchName }}
+          PR_BRANCH: ${{ env.newBranchName }}
           PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
-          PR_BODY: "${{ format('Cherry pick from the original PR: \n- #{0}\n\n ---- \n\n Conflicts during cherry-pick:\n {2} \n\n{1}', github.event.pull_request.number, github.event.pull_request.body, steps.cherry.outputs.conflicts) }}"
-        run: gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head $PR_BRANCH --label "cherry-pick" --assignee "$PR_ASSIGNEE"
+        run: |
+          set -x
+          if [ -n "${{ env.conflicts }}" ]; then
+              echo "---- \n\n ⚠️ Conflicts during cherry-pick:\n${{ env.conflicts }}\n\n" > CONFLICTS_MESSAGE
+          else
+              echo "" > CONFLICTS_MESSAGE
+          fi
+          CONFLICTS_MESSAGE=$(cat CONFLICTS_MESSAGE)
+          PR_BODY="${{ format('Cherry pick from the original PR: \n- #{0}\n\n{1}{2}', github.event.pull_request.number, CONFLICTS_MESSAGE, github.event.pull_request.body) }}"
+          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head "$PR_BRANCH" --label "cherry-pick" --assignee "$PR_ASSIGNEE"
