fix

diff --git a/.github/workflows/cherry-pick-rc-to-develop.yml b/.github/workflows/cherry-pick-rc-to-develop.yml
--- a/.github/workflows/cherry-pick-rc-to-develop.yml
+++ b/.github/workflows/cherry-pick-rc-to-develop.yml
@@ -40,19 +40,22 @@ jobs:
           git checkout -b ${{ env.newBranchName }} develop
           # Cherry-picking the last commit on the base branch
           OUTPUT=$(git cherry-pick ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true)
-          echo "$OUTPUT"
           CONFLICTS=$(echo "$OUTPUT" | grep 'CONFLICT' || echo "")
-          echo "CONFLICTS=$CONFLICTS" >> $GITHUB_ENV
+          echo "conflicts=$CONFLICTS" >> $GITHUB_ENV
           git add .
-          echo "git add"
-          git cherry-pick --continue || echo "No cherry-pick in progress"
-          echo "cherry-pick --continue"
-          git push origin ${{ env.newBranchName }} || (echo "Failed to push to origin" && exit 1)
+          git cherry-pick --continue || true
+          git push origin ${{ steps.extract.outputs.newBranchName }} || (echo "Failed to push to origin" && exit 1)
 
       - name: Create PR
         env:
           PR_TITLE: ${{ github.event.pull_request.title }}
           PR_BRANCH: ${{ env.newBranchName }}
           PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
-          PR_BODY: "${{ format('Cherry pick from the original PR: \n- #{0}\n\n ---- \n\n ⚠️ Conflicts during cherry-pick:\n {2} \n\n{1}', github.event.pull_request.number, github.event.pull_request.body, env.conflicts) }}"
-        run: gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head $PR_BRANCH --label "cherry-pick" --assignee "$PR_ASSIGNEE"
+        run: |
+          if [[ -n "${{ steps.cherry.outputs.conflicts }}" ]]; then
+             CONFLICTS_MESSAGE="\n\n ---- \n\n ⚠️ Conflicts during cherry-pick:\n${{ env.conflicts }}\n\n"
+           else
+             CONFLICTS_MESSAGE=""
+           fi
+          PR_BODY="${{ format('Cherry pick from the original PR: \n- #{0}{1}{2}', github.event.pull_request.number, CONFLICTS_MESSAGE, github.event.pull_request.body) }}"
+          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head $PR_BRANCH --label "cherry-pick" --assignee "$PR_ASSIGNEE"
